### PR TITLE
Device tree

### PR DESCRIPTION
**Pull request by jenswikl**
Don't add optee node or reserve secure world uart.

Depends on https://github.com/OP-TEE/optee_os/pull/856

### CODE REVIEW

**Comment by jockebech** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswikl** [comment]
Reviving this PR with another patch needed to make paging work again after https://github.com/OP-TEE/optee_os/pull/1236

**Comment by jenswikl** [comment]
Ping?

**Comment by jockebech** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswikl** [comment]
Tag applied

**Pull request merged**
